In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
print("Numpy array from list:")
print(a)

Numpy array from list:
[1 2 3 4 5]


In [3]:
b = np.array((1,2,3,4,5))
print("Numpy array from tuple:")
print(b)

Numpy array from tuple:
[1 2 3 4 5]


In [4]:
c = np.array({1,2,3,4,5})
print("Numpy array from set:")
print(c)

Numpy array from set:
{1, 2, 3, 4, 5}


In [5]:
zeros_array = np.zeros((2,3))
print(zeros_array)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
X = np.ones((3,2))
print(X)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [8]:
P = np.random.rand(3,3)
print("Random array:\n",P)

Random array:
 [[0.02834891 0.44070637 0.58652098]
 [0.31091181 0.41042012 0.18767527]
 [0.46814253 0.84928174 0.75380324]]


In [9]:
Q = np.random.randint(1,10,size=(2,3))
print("Random array:\n",Q)

Random array:
 [[1 5 1]
 [6 2 7]]
