In [1]:
import numpy as np

In [2]:
array = np.arange(12).reshape(3,4)
print("Original Array;\n",array)

Original Array;
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
print("Indexing:")
print("Element at (1,2):",array[1,2])
print("First row:",array[0])
print("Last column:",array[:,-1])

Indexing:
Element at (1,2): 6
First row: [0 1 2 3]
Last column: [ 3  7 11]


In [4]:
print('Slicing:')
print("First two rows:\n",array[:2,:])
print("Last two columns:\n",array[:,-2:])

Slicing:
First two rows:
 [[0 1 2 3]
 [4 5 6 7]]
Last two columns:
 [[ 2  3]
 [ 6  7]
 [10 11]]


In [5]:
print("Reshaping:")
print("Reshaped Array:\n",array.reshape(2,6))

Reshaping:
Reshaped Array:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [6]:
print("Joining:")
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[5,6],[7,8]])
print("Verically stacked arrays:\n",np.vstack((a1,a2)))
print("Horizontally stacked arrays:\n",np.hstack((a1,a2)))

Joining:
Verically stacked arrays:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Horizontally stacked arrays:
 [[1 2 5 6]
 [3 4 7 8]]


In [7]:
print("Splitting:")
split_array = np.arange(16).reshape(4,4)
print("Original Array:\n",split_array)

Splitting:
Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [8]:
split_arrays = np.hsplit(split_array,2)
print("Split Arrays:")
for arr in split_array:
    print(arr)

Split Arrays:
[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]
[12 13 14 15]
