In [1]:
import numpy as np

In [2]:
data = np.genfromtxt('data.csv',delimiter=',',skip_header=1)
print("Data:\n",data)

Data:
 [[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [3]:
print("Mean of each column:",np.mean(data,axis=0))
print("Standard deviation of each row:",np.std(data,axis=1))

Mean of each column: [5. 6. 7. 8.]
Standard deviation of each row: [1.11803399 1.11803399 1.11803399]


In [4]:
comparison = data>5
print('Comparison with 5:\n',comparison)
print('\nElements greater than 5:\n',data[data>5])

Comparison with 5:
 [[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]

Elements greater than 5:
 [ 6.  7.  8.  9. 10. 11. 12.]


In [5]:
print('Sum of each column:',np.sum(data,axis=0))
print('Sum of each row:',np.sum(data,axis=1))

Sum of each column: [15. 18. 21. 24.]
Sum of each row: [10. 26. 42.]
